### PR TITLE
Add Tests for Entity and Use Cases

### LINKED ISSUE #51: Add Test for Entity and Use case

### PR DESCRIPTION
**Pull request by TingmingFan**
## Description
Add test for each Entity and Use Case. Make sure all the tests pass and notify/raise an issue when find bugs exist in backend methods. Provide Javadoc and Display Name for each test to make the code more readable and easy to keep track of pass/fail. #51 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by donnaqi — DISMISSED** [review]

**Review by yyuan-qin — DISMISSED** [review]
All the tests look good! Good job

**Review by AdwinTazement — DISMISSED** [review]

**Review by sanciag17 — DISMISSED** [review]
Good job on following clean architecture and making sure the tests run properly.

**Review by AdwinTazement — APPROVED** [review]

**Review by lisacheng12 — APPROVED** [review]
Good work with adding the test for entities and use cases. However, I think it would be better to delete some empty line in the test get warning messgae file to make the code cleaner.

**Comment by AdwinTazement** [comment]
The tests are clear and annotations make them easy to understand. All setups and tests are correct and the tests carefully tested every conditions the entities and usecases are used. Nice work.

**Review by donnaqi — APPROVED** [review]

**Review by lisacheng12 — COMMENTED** [review]
I think some of the files would require more documentations.

**Review by yyuan-qin — APPROVED** [review]

**Pull request merged**
