### PR TITLE
Feature 1 finalize

### PR DESCRIPTION
**Pull request by yyuan-qin**
## Description
Finalize the entire feature 1 relates to Issue #1 for the Login, Register and reset password screen.
Implement the Customer Main page and connect to other frame such as "Drink layout", "Search Drink" (Issue #3) and "Sale Section" (Issue #5).
Add documantation to make the code more readable.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by sanciag17 — DISMISSED** [review]
Good job on finalizing and following clean architecture!

**Review by donnaqi — DISMISSED** [review]
I have fixed most bugs, the only existing error relates to SellerMainScreen. Once the SellerMainScreen get implemented, this error should be resolved.

**Review by TingmingFan — DISMISSED** [review]

**Review by donnaqi — CHANGES_REQUESTED** [review]
Your local branch did not rebase main, you need to change it to the correct version.

**Review by donnaqi — DISMISSED** [review]

**Review by sanciag17 — APPROVED** [review]

**Review by donnaqi — APPROVED** [review]

**Review by AdwinTazement — APPROVED** [review]

**Review by lisa272 — COMMENTED** [review]
Good work for completing the customer main page

**Pull request merged**
