### PR TITLE
[FEATURE] #1 Register & Login

### PR DESCRIPTION
**Pull request by donnaqi**
## Description
- Add User, Customer, Seller classes with constructors.
- Add UserController: Use user HashMap to store or extract data from database.
- Add helper Serializer and Deserializer: store object into or extract object from the given file path.
- Partially finished Issue #1 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by yuanjiat — DISMISSED** [review]
All good.

**Review by lisa272 — DISMISSED** [review]
Successfully create the base entities of this project and complete the login register part.

**Comment by AdwinTazement** [comment]
nice

**Review by AdwinTazement — DISMISSED** [review]
nice

**Review by AdwinTazement — APPROVED** [review]
nicee

**Review by yuanjiat — APPROVED** [review]
Excellent work

**Review by lisa272 — APPROVED** [review]
Adding the base code for entities

**Pull request merged**
