### PR TITLE
Feature4 backend

### PR DESCRIPTION
**Pull request by donnaqi**
## Description
Implement SearchDrinks features for Issue #3 so the customers can search drinks by keyword that exists in drink attributes such as drink name, descrpition, etc.
Implement AddToShoppingCart features to make sure customers can add drinks from "Drinks layout" page and "Search drinks" page to the shopping cart, and update the customer attribute shopping cart.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by TingmingFan — DISMISSED** [review]
Reconstruct instance of the entity drink, some variable type changes and added hashmap in the customer class. implemented the screen, backend of search drink(feature 4), and modifying items prices, names and quantity(feature 2), lot of work has been done.

**Review by yyuan-qin — COMMENTED** [review]
Everything looks good! Just change the addItem function such that it would detect is a Drink is already in the Hashmap and would increment the quantity instead of adding the Drink again.

**Comment by donnaqi** [comment]
> Everything looks good! Just change the addItem function such that it would detect is a Drink is already in the Hashmap and would increment the quantity instead of adding the Drink again.

Good catch! Will fix this part now.

**Review by yyuan-qin — APPROVED** [review]

**Review by sanciag17 — APPROVED** [review]
Nice job on adding the classes and following clean architecture!

**Review by yuanjiat — APPROVED** [review]

**Pull request merged**
